### ISSUE TITLE
提交簡報雛形

### ISSUE THREAD

**Issue by howard9199** [CSIE-Camp/Tracker#15]
**任務要求:**
將教學內容簡單做成簡報，之後會找時間請大家用口頭帶過，主要會確認以下幾件事:
1. (必要)教學內容安排是否完整(有沒有順序反過來、中間跳過哪些東西、哪些地方帶實作等)
2. (必要)教學時間預計怎麼安排(這個部分需要花多少時間)
3. (視個人)簡報製作的建議，如果你交出來的簡報不是隨便放的話

Ckpt. C 才需要產生一份完整的簡報，所以這裡做不完沒關係，我們會就你目前的進度給建議
請將簡報上傳至下方

**歷屆簡報製作參考:**
A. PPT: https://docs.google.com/presentation/d/1GEwHjbaOut6E8IBLJJErfzLOvM4Pn1T-/edit?usp=share_link&ouid=114860704601803546966&rtpof=true&sd=true
B. Slides.com: https://slides.com/ntnucsie/algobang
C. Hackmd: https://hackmd.io/@SubaRya/SkgBKs6E9#/ 
D. js: https://slides.jacoblin.cool/
E. Canva.com

各工具的特點:
B. Slides.com:
1. 可以同步簡報頁面，觀眾也可以自己任意切換，不須廣播畫面
2. 程式碼高亮
3. 可以用手機遠端控制簡報畫面

C. Hackmd:
1. 程式碼高亮
2. 聽說有簡報模式，可以同步畫面
3. 排版上比較難自由發揮

D. js:
1. 非常非常的自由，你想幹嘛就幹嘛

E. Canva.com:
1.  模板超級多，文組生首選品牌

**其他參考資料:**
https://hackmd.io/@Adam7066/cyberbug2021-ppt#/

**Comment by Maxxxxxx-x** [comment]
https://docs.google.com/presentation/d/14kcb037buDx71O0omh2gc3GJt0qBbaSGgcSHSB3r2Ts/edit#slide=id.g1e65c7ff29d_0_385

**Comment by Maxxxxxx-x** [comment]
https://docs.google.com/presentation/d/14kcb037buDx71O0omh2gc3GJt0qBbaSGgcSHSB3r2Ts/edit#slide=id.g1e65c7ff29d_0_385

**Comment by hjkplus** [comment]
https://docs.google.com/presentation/d/1jXbSxZJAJlviiR2T3z9kS6ou_2YeWscKAlJx3Et-YdQ/edit?usp=sharing

**Comment by othsueh** [comment]
https://hackmd.io/@oth/ByXl8N8ij

**Comment by Dannygod** [comment]
[連結](https://docs.google.com/presentation/d/1mZ37JV0EVHbap4lGiKeZSypxeyld-5kp4Q3k25VmO9U/edit#slide=id.g1c13a0f47f5_0_0)

**Comment by ryan-huang-1213** [comment]
[js基本語法.pptx](https://github.com/CSIE-Camp/Tracker/files/10471598/js.pptx)

**Comment by UltraSheep** [comment]
[https://docs.google.com/presentation/d/1ubl2u42eP1jKoNetJeUJyH7ily3WRsg6TNS9wYG_Low/edit?usp=sharing](url)

**Comment by Alphabeee** [comment]
[discordbot.pptx](https://github.com/CSIE-Camp/Tracker/files/10471603/discordbot.pptx)
