### ISSUE TITLE
提交完整簡報

### ISSUE THREAD

**Issue by howard9199** [CSIE-Camp/Tracker#16]
**任務要求:**
「完成所有的簡報」，而且簡報內必須包含以下內容:

1. 引起動機，讓他們提高這堂課的興趣(除非你的課程主題是如何脫離失眠的困擾)
2. 自我介紹(除非你想當個隱士)
3. Ckpt. B 的回饋，連結:https://hackmd.io/@howchien/ckptb (除非開學後想體驗一下金門菜刀的威力?)
另外，我們也會對時間安排做最後確認哦

最後，歡迎各位可以準備講稿，下次在教學的時候會容易許多哦~
**提醒: 請確認檔案有沒有開權限**

**Comment by othsueh** [comment]
[Slide](https://slides.com/othsueh/deck-838e36)

**Comment by Alphabeee** [comment]
[discord bot.pptx](https://github.com/CSIE-Camp/Tracker/files/10729004/discord.bot.pptx)

**Comment by UltraSheep** [comment]
[https://docs.google.com/presentation/d/1ubl2u42eP1jKoNetJeUJyH7ily3WRsg6TNS9wYG_Low/edit?usp=sharing](url)

**Comment by ryan-huang-1213** [comment]
[js基本語法.pptx](https://github.com/CSIE-Camp/Tracker/files/10739475/js.pptx)
[Uploading js基本語法.pptx…]()

**Comment by Dannygod** [comment]
[簡報](https://docs.google.com/presentation/d/1mZ37JV0EVHbap4lGiKeZSypxeyld-5kp4Q3k25VmO9U/edit?usp=sharing)

**Comment by Maxxxxxx-x** [comment]
https://docs.google.com/presentation/d/163AV-TbMJbPFbkBLkwf8El20t8blTosQiFF7AR6Dh3Q/edit?usp=sharing

**Comment by hjkplus** [comment]
完整版: https://docs.google.com/presentation/d/1jXbSxZJAJlviiR2T3z9kS6ou_2YeWscKAlJx3Et-YdQ/
精簡版: https://docs.google.com/presentation/d/19wxE6KN3D2sI7zzpyXd8gv_9stgAYt8x4Nix5nkhFpU

**Comment by hjkplus** [comment]
詞彙表: https://docs.google.com/spreadsheets/d/19mzSkvomc1TP4mDk_5FuFX077Cg7Ovgq_9Lk7M550gc/edit?usp=sharing

**Comment by hjkplus** [comment]
超簡版: https://docs.google.com/presentation/d/1g2eM1ANl_yYlX85etceVUOhkkx-Wgf0WuE3_oSiuevc/edit?usp=sharing

**Comment by othsueh** [comment]
[new report](https://slides.com/d/96tzPe8/live)
