### ISSUE TITLE
Ckpt. C 回饋與「好」的簡報

### ISSUE THREAD

**Issue by howard9199** [CSIE-Camp/Tracker#17]
**任務說明:**
1. 將 Ckpt. C 給的回饋(https://hackmd.io/@howchien/ckptc) 加入簡報，如果對回饋有問題可以問我們哦
2. 檢查一下是否符合「好」的簡報，可以參考一下你們自己在 Slido 寫的哦
https://media.discordapp.net/attachments/894848956897570876/1077575198007640096/image.png?width=1154&height=671

做完後請在 **3/3(五) 23:59:59** 前將簡報上傳於此。

**Comment by othsueh** [comment]
[Presentation Link](https://slides.com/d/96tzPe8/live)

**Comment by Maxxxxxx-x** [comment]
[Very Safe Link](https://1drv.ms/p/s!Am_Fu67tG5Vok7R9LrjcoZo5pt_YPQ?e=YN6kGb)

**Comment by Dannygod** [comment]
[Web Design](https://docs.google.com/presentation/d/1mZ37JV0EVHbap4lGiKeZSypxeyld-5kp4Q3k25VmO9U/edit?usp=sharing)

**Comment by UltraSheep** [comment]
[Free ROBUX](https://docs.google.com/presentation/d/1ubl2u42eP1jKoNetJeUJyH7ily3WRsg6TNS9wYG_Low/edit?usp=sharing)

**Comment by Alphabeee** [comment]
[discord bot.pptx](https://github.com/CSIE-Camp/Tracker/files/10942267/discord.bot.pptx)

**Comment by ryan-huang-1213** [comment]
[js基本語法.pptx](https://github.com/CSIE-Camp/Tracker/files/10883793/js.pptx)

**Comment by ryan-huang-1213** [comment]
[js基本語法.pptx](https://github.com/CSIE-Camp/Tracker/files/10942275/js.pptx)
