### ISSUE TITLE
Ckpt. D 上傳試教簡報

### ISSUE THREAD

**Issue by howard9199** [CSIE-Camp/Tracker#18]

**Comment by hjkplus** [comment]
超簡版: https://docs.google.com/presentation/d/1g2eM1ANl_yYlX85etceVUOhkkx-Wgf0WuE3_oSiuevc/edit?usp=sharing

**Comment by Dannygod** [comment]
[Web Design](https://docs.google.com/presentation/d/1mZ37JV0EVHbap4lGiKeZSypxeyld-5kp4Q3k25VmO9U/edit?usp=sharing)

**Comment by UltraSheep** [comment]
[Double your bitcoin here](https://docs.google.com/presentation/d/1ubl2u42eP1jKoNetJeUJyH7ily3WRsg6TNS9wYG_Low/edit?usp=sharing)

**Comment by ryan-huang-1213** [comment]
[js基本語法.pptx](https://github.com/CSIE-Camp/Tracker/files/11060147/js.pptx)

**Comment by Maxxxxxx-x** [comment]
SQL (+ SQLi)
https://1drv.ms/p/s!AgG2FGETITnUgRwEiYo6iK91wXL1?e=dQaRsf

**Comment by Alphabeee** [comment]
https://1drv.ms/p/s!Ahq0tktMKe48gZ0v3-lFf095M5mBjA?e=zrDTFE

**Comment by howard9199** [comment]
DONE.

**Comment by othsueh** [comment]
[report](https://slides.com/othsueh/deck-838e36)
