### ISSUE TITLE
各組選定教學主題

### ISSUE THREAD

**Issue by JacobLinCool** [CSIE-Camp/Tracker#5]
各組選定教學主題。

完成狀況：

- [x] Maxx
- [x] 余竣學
- [x] Plus
- [x] 林柏宏
- [x] 蕭文洋
- [x] 許宸研
- [x] 黃國展

**Comment by Maxxxxxx-x** [comment]
Category: Cyber Security

Topics:
SQL Injection
XSS Attacks
MiTM attacks
Timing attacks

**Comment by howard9199** [comment]
@吳俊熙 (Maxxxxxxxxxxx) Cyber Security(資安組) 2
@李赫珈 Basic Cryptography(資安組) 2
@許宸研 Web Design(網頁組) 4~5
@余竣學 Github Page Blog(網頁組) ?

Discord Bot:
@黃國展（ryan) Basic
@林柏宏 @蕭文洋（羊）Advance 3
