### ISSUE TITLE
確認所有股員都加入組織

### ISSUE THREAD

**Issue by JacobLinCool** [CSIE-Camp/Tracker#8]
- [x] @JacobLinCool 
- [x] @howard9199 
- [x] @Maxxxxxx-x
- [x] @othsueh
- [x] @brian8956
- [x] @hjkplus
- [x] @Alphabeee
- [x] @UltraSheep
- [x] @Dannygod
- [x] @ryan-huang-1213

**Comment by UltraSheep** [comment]
o7

**Comment by ryan-huang-1213** [comment]
hi

**Comment by JacobLinCool** [comment]
> hi

Hi 記得去收邀請函：https://github.com/CSIE-Camp

**Comment by JacobLinCool** [comment]
done.
